language: generic
matrix:
  include:
    - script:
        - xcodebuild -scheme Yams build-for-testing test-without-building # -sdk macosx -destination arch=x86_64
        - xcodebuild -scheme Yams build-for-testing test-without-building OTHER_SWIFT_FLAGS=-DUSE_UTF8
        - xcodebuild -scheme Yams build-for-testing test-without-building -sdk iphonesimulator -destination "name=iPhone 6s"
        - xcodebuild -scheme Yams build-for-testing test-without-building -sdk appletvsimulator -destination "name=Apple TV 1080p"
        - xcodebuild -scheme Yams build -sdk watchsimulator -destination "name=Apple Watch - 38mm"
        - pod lib lint
      env: JOB=Xcode8.2
      os: osx
      osx_image: xcode8.2
    - script:
        - xcodebuild -scheme Yams build-for-testing test-without-building # -sdk macosx -destination arch=x86_64
        - xcodebuild -scheme Yams build-for-testing test-without-building OTHER_SWIFT_FLAGS=-DUSE_UTF8
        - xcodebuild -scheme Yams build-for-testing test-without-building -sdk iphonesimulator -destination "name=iPhone 6s"
        - xcodebuild -scheme Yams build-for-testing test-without-building -sdk appletvsimulator -destination "name=Apple TV 1080p"
        - xcodebuild -scheme Yams build -sdk watchsimulator -destination "name=Apple Watch - 38mm"
        - pod lib lint
      env: JOB=Xcode8.3
      os: osx
      osx_image: xcode8.3
      before_install:
        - xcrun simctl delete 38C891AB-EC79-43E4-9311-6FDEB12DCF11 || true
    - script:
        - swift test
        - swift test -Xswiftc -DUSE_UTF8
        - swiftlint
      env: JOB=SPM-Swift3.0.2
      os: osx
      osx_image: xcode8.2
    - script:
        - swift test
        - swift test -Xswiftc -DUSE_UTF8
        - swiftlint
      env: JOB=SPM-Swift3.1
      os: osx
      osx_image: xcode8.3
    - script:
        - docker run -v `pwd`:`pwd` -w `pwd` --rm $DOCKER_IMAGE swift test
        - docker run -v `pwd`:`pwd` -w `pwd` --rm $DOCKER_IMAGE swift test -Xswiftc -DUSE_UTF8
      env:
        - JOB=Docker
        - DOCKER_IMAGE=swift:3.0.2
      sudo: required
      services: docker
    - script:
        - docker run -v `pwd`:`pwd` -w `pwd` --rm $DOCKER_IMAGE swift test
        - docker run -v `pwd`:`pwd` -w `pwd` --rm $DOCKER_IMAGE swift test -Xswiftc -DUSE_UTF8
      env:
        - JOB=Docker
        - DOCKER_IMAGE=swift:3.1
      sudo: required
      services: docker
    - script:
        - docker run -v `pwd`:`pwd` -w `pwd` --rm $DOCKER_IMAGE swift test
        - docker run -v `pwd`:`pwd` -w `pwd` --rm $DOCKER_IMAGE swift test -Xswiftc -DUSE_UTF8
      env:
        - JOB=Docker
        - DOCKER_IMAGE=norionomura/swift:4020170623a
      sudo: required
      services: docker
notifications:
  email: false
