name: Bazel

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/bazel.yml'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'
      - 'Tests/**/*.swift'
      - 'Tests/**/*.ya?ml'
      - '**/BUILD'
      - 'WORKSPACE'
      - '.bazelrc'
      - '.bazelversion'
  pull_request:
    paths:
      - '.github/workflows/bazel.yml'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'
      - 'Tests/**/*.swift'
      - 'Tests/**/*.ya?ml'
      - '**/BUILD'
      - 'WORKSPACE'
      - '.bazelrc'
      - '.bazelversion'

jobs:
  MacOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: MacOS build test
        if: always()
        run: bazelisk test //Tests:macOSBuildTest
        shell: bash
      - name: WatchOS build test
        if: always()
        run: bazelisk test //Tests:watchOSBuildTest
        shell: bash
      - name: iOS build test
        if: always()
        run: bazelisk test //Tests:iOSBuildTest
        shell: bash
      - name: tvOS build test
        if: always()
        run: bazelisk test //Tests:tvOSBuildTest
        shell: bash
      - name: Yams tests
        if: always()
        run: bazelisk test //Tests:UnitTests
        shell: bash
  Linux:
    strategy:
      matrix:
        tag: ['5.4', '5.5', '5.6']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.tag }}-focal
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Yams tests
        run: bazel test --test_output=all //Tests:UnitTests
