name: pod lib lint

on:
  push:
    branches: [main]
    paths: 
      - '.github/workflows/pod_lib_lint.yml'
      - '*.podspec'
      - 'Gemfile*'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'
  pull_request:
    paths: 
      - '.github/workflows/pod_lib_lint.yml'
      - '*.podspec'
      - 'Gemfile*'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'

jobs:
  pod_lib_lint:
    name: pod lib lint
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.app
    steps:
      - uses: actions/checkout@v3
      - run: bundle install --path vendor/bundle
      - run: bundle exec pod lib lint --verbose
